server:
  port: 1111
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4000/eureka/
      
spring:
  application:
    name: user
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: test