server:
  port: 8181
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4000/eureka/
      
spring:
  application:
    name: APIGateway
    
zuul:
  routes:
    r1:
      path: /user/**
      serviceId: user
    r2:
      path: /talk/**
      serviceId: talk
    